# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: student.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rstudent.proto\x12\x06Protos\x1a\x1fgoogle/protobuf/timestamp.proto\"\x86\x01\n\x07Student\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\'\n\x03\x64ob\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x1f\n\x07\x63ourses\x18\x05 \x03(\x0b\x32\x0e.Protos.Course\"%\n\x06\x43ourse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x05\x62\x06proto3')



_STUDENT = DESCRIPTOR.message_types_by_name['Student']
_COURSE = DESCRIPTOR.message_types_by_name['Course']
Student = _reflection.GeneratedProtocolMessageType('Student', (_message.Message,), {
  'DESCRIPTOR' : _STUDENT,
  '__module__' : 'student_pb2'
  # @@protoc_insertion_point(class_scope:Protos.Student)
  })
_sym_db.RegisterMessage(Student)

Course = _reflection.GeneratedProtocolMessageType('Course', (_message.Message,), {
  'DESCRIPTOR' : _COURSE,
  '__module__' : 'student_pb2'
  # @@protoc_insertion_point(class_scope:Protos.Course)
  })
_sym_db.RegisterMessage(Course)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STUDENT._serialized_start=59
  _STUDENT._serialized_end=193
  _COURSE._serialized_start=195
  _COURSE._serialized_end=232
# @@protoc_insertion_point(module_scope)
